version: '3.8'

services:
  keycloak:
    container_name: keycloak
    cpus: 0.5
    mem_reservation: 1G
    mem_limit: 1G
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    image: jboss/keycloak:16.1.1
    expose:
      - '8443'
      - '8080'
      - '9990'
    ports:
      - '127.0.0.1:8443:8443'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:9990:9990'
    volumes:
      - $PWD/data:/opt/jboss/keycloak/standalone/data
    networks:
      - default
    restart: unless-stopped

  manager:
    container_name: manager
    cpus: 0.5
    mem_reservation: 1G
    mem_limit: 1.5G
    image: keycloak_mng:latest
    ports:
      - 8088:3000
    volumes:
      - $PWD/data:/var/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_BASE_URL=http://keycloak:8080/auth
      - PORT=3000
    networks:
      - default
    restart: always
